title: Mike Trpcic
description: "Coder, Manager, and Technoloy Enthusiast"

url: https://mtrpcic.net
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: pygments

gems:
  - jekyll-paginate
  - jekyll-redirect-from

whitelist:
  - jekyll-paginate
  - jekyll-redirect-from

paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: Series
   url: /series
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: mtrpcic
   twitter: mtrpcic
   email: mike@mtrpcic.net

google_analytics: "UA-60246214-1"
